#!MANAGED-CONFIG https://raw.githubusercontent.com/rsivanov-git/surge/main/DefaultTailnet.conf
[General]
loglevel = warning
udp-policy-not-supported-behaviour = REJECT
dns-server = system

[Host]
ntc.party = 130.255.77.28

[Proxy Group]
PROXY = select, DIRECT, REJECT

[Rule]
DOMAIN,_test.local,REJECT,pre-matching
# Russia
RULE-SET,https://surge.bojin.co/geosite/full/category-ru,PROXY
GEOIP,RU,PROXY,no-resolve
# Final
FINAL,DIRECT
