#!MANAGED-CONFIG https://raw.githubusercontent.com/rsivanov-git/surge/main/DefaultTailnet.conf
[General]
loglevel = warning
udp-policy-not-supported-behaviour = REJECT
dns-server = system

[Host]
ntc.party = 130.255.77.28

[Rule]
DOMAIN,_test.local,REJECT,pre-matching
# Final
FINAL,DIRECT
