name: Notify Private Repo

on:
  push:
    branches:
      - main

jobs:
  notify_private_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Send repository dispatch event
      uses: peter-evans/repository-dispatch@v3.0.0
      with:
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        repository: rsivanov-git/surge-personal
        event-type: public-repo-updated
